apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-ojnk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-ojnk
    app.kubernetes.io/part-of: all-samples-as-components
  name: devfile-sample-go-basic-ojnk
  namespace: jephilli-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-go-basic-ojnk
status:
  loadBalancer: {}
